# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: trailing-whitespace
            verbose: true
            exclude: ^notebooks
        -   id: end-of-file-fixer
            verbose: true
            exclude: ^notebooks
        -   id: check-yaml
            verbose: true
            exclude: ^notebooks
        -   id: check-case-conflict
            verbose: true
            exclude: ^notebooks
        -   id: debug-statements
            verbose: true
            exclude: ^notebooks
        -   id: detect-private-key
            verbose: true
            exclude: ^notebooks
        -   id: check-merge-conflict
            verbose: true
            exclude: ^notebooks
        -   id: check-added-large-files
            verbose: true
            exclude: ^notebooks
    -   repo: https://github.com/myint/autoflake
        rev: v1.4
        hooks:
        -   id: autoflake
            verbose: true
            exclude: ^notebooks
            args:
              - --in-place
              - --remove-duplicate-keys
              - --remove-unused-variables
              - --remove-all-unused-imports
              - --expand-star-imports
    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            verbose: true
            exclude: ^notebooks
            args:
              - --profile
              - black
    -   repo: https://github.com/ambv/black
        rev: 22.6.0
        hooks:
        -   id: black
            verbose: true
            exclude: ^notebooks
