# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-case-conflict
        -   id: debug-statements
        -   id: detect-private-key
        -   id: check-merge-conflict
        -   id: check-added-large-files

    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            args:
              - --profile
              - black

    -   repo: https://github.com/asottile/seed-isort-config
        rev: v1.9.3
        hooks:
        -   id: seed-isort-config

    -   repo: https://github.com/ambv/black
        rev: 22.6.0
        hooks:
        -   id: black
            language_version: python3.10

    -   repo: https://github.com/john-hen/Flake8-pyproject
        rev: 1.0.0
        hooks:
        -   id: Flake8-pyproject
            args:
              - --check
              - --in-place
              - --remove-duplicate-keys
              - --remove-unused-variables
              - --remove-all-unused-imports
              - --expand-star-imports
