[tool.black]
extend-exclude = '''
## A regex preceded with ^/ will apply only to files and directories
## in the root of the project.
(
  ^/notebooks  # exclude notebooks folder
)
'''
include = '\.pyi?$'
line-length = 160


[tool.flake8]
count = true
extend-exclude = ['data/*', 'docs/*', 'notebooks/*', 'output/*']
ignore = ['E231', 'E241', 'E701']
max-line-length = 160
statistics = true


[tool.isort]
known_third_party = ["dotenv", "fastapi", "mba_tcc", "pandas", "prefect", "prefect_dask", "utils"]
include_trailing_comma = true
line_length = 160
profile = 'black'
skip_glob = ['notebooks/*']
src_paths = ['pipelines', 'serve']
